version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain dependencies for the project
  - package-ecosystem: "npm"
    directories:
      # Update the package.json and lock file at the root as well as the ones in
      # /packages/diracx-web and /packages/diracx-web-extensions
      - "/"
      # Update the package.json and lock file in /packages/extensions
      - "/packages/extensions"
    schedule:
      interval: "weekly"
    versioning-strategy: increase