title: "[<Community Name>] <Feature Request>"
body:
  - type: markdown
    attributes:
      value: >
        Develop a user persona and a story to capture the goals and tasks your users want to accomplish with diracx-web.
        We are interested in understanding your needs and goals. Please, first focus on what you want to achieve rather than how you think it should be achieved first.
        All ideas are welcome, and there are no wrong answers. We appreciate your honest feedback as it helps us improve the system to better meet your needs.

  - type: textarea
    id: user-persona
    attributes:
      label: User Persona
      description: |
        Who is the user? Here is an example:
        - Technical proficiency: Novice | Intermediate | Advanced | Expert
        - Occupation: Dirac Developer
        - Goals: 
          1. Ease eye strain during long working hours by utilizing a dark mode feature.
          2. Improve focus and productivity by reducing glare and distraction from a bright screen.
          3. Maintain a sleek and modern user interface.
        - Pain points:
          1. Current bright/light theme of the web app causes eye fatigue, especially when working late into the night.
          2. The lack of a dark mode feature feels outdated and not in alignment with contemporary design standards.
          3. Concerned that continued use of the app in its current state may adversely affect my vision over time.
      value: |
        - Technical proficiency:
        - Occupation:
        - Goals:
        - Pain points:
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: |
        What does the user want to achieve in this scenario? Here is an example:
        As a developer, John wants a dark mode feature in the web app so that he can work comfortably during late hours and reduce eye strain, while also enjoying a modern and sleek user interface.
      placeholder: |
        As a [type of user], [User] wants [an action] so that [a benefit/a goal].
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        From this point, you can optionally propose ideas of how it should be conceived, even if you technically do not know whether it is achievable.

  - type: textarea
    id: design-solution
    attributes:
      label: Proposed Design Solution
      description: |
        Design proposal(s) can be submitted here.
        Explain how your design solves the problem. Describe the design changes in details.
      placeholder: "Describe your design solution..."

  - type: markdown
    attributes:
      value: |
        If possible, please attach an image representing a mockup or sketch of your design idea. Visual representations can help communicate your idea more clearly.

  - type: markdown
    attributes:
      value: |
        Once again, thank you for your contribution. Our team will review your design proposal(s) and provide feedback.

