name: Deployment

on:
  push:
    branches-ignore:
      - dependabot/**
      - release-please-**
  pull_request:
    branches-ignore:
      - release-please-**

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.repository == 'DIRACGrid/diracx-web' }}
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: ${{ github.ref_name }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  build-deploy-library-package:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ github.event_name == 'push' && github.repository == 'DIRACGrid/diracx-web' && needs.release-please.outputs.release_created == 'true' }}
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@diracgrid'

    - name: Install dependencies
      run: npm ci

    # Release Please has already incremented versions and published tags, so we just
    # need to publish all unpublished versions to GitHub here
    - name: Publish to GitHub Packages
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx lerna publish from-package --no-push --no-private --yes

  build-deploy-dev-image:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' || github.repository == 'DIRACGrid/diracx-web' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (dev)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'push' && github.repository == 'DIRACGrid/diracx-web' && github.ref_name == 'main' }}
          tags: ghcr.io/diracgrid/diracx-web/static:dev
          platforms: linux/amd64,linux/arm64

  build-deploy-release-image:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.repository == 'DIRACGrid/diracx-web' }}
    needs: release-please
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        if: ${{ needs.release-please.outputs.release_created == 'true' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/diracgrid/diracx-web/static:${{ needs.release-please.outputs.tag_name }}
          platforms: linux/amd64,linux/arm64