name: DiracX-Web Components Tests

on:
  push:
    paths:
      - 'packages/diracx-web-components/**'
      - 'package.json'
      - 'package-lock.json'
    branches-ignore:
      - dependabot/**
      - release-please-**
  pull_request:
    paths:
      - 'packages/diracx-web-components/**'
      - 'package.json'
      - 'package-lock.json'
    branches-ignore:
      - release-please-**

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.repository == 'DIRACGrid/diracx-web'
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
              
      - name: Trigger unit tests
        run: npm --prefix packages/diracx-web-components run test
