name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.repository == 'DIRACGrid/diracx-web'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
              
      - name: Trigger tests
        run: npm run test
